import React, { useState, useEffect, useRef } from "react";
import { api } from "../services/api";
import { AIReport, User, Child } from "../types";
import { motion, AnimatePresence } from "motion/react";
import { Search, Printer, Mail, Share2, ArrowLeft, Download, ShieldCheck, Heart, Sparkles, BookOpen, AlertTriangle, FileText, Check, Calendar, Activity, X } from "lucide-react";
import { jsPDF } from "jspdf";

interface AIHistoryProps {
  user: User;
  addToast: (title: string, message: string, type: 'success' | 'error' | 'warning' | 'info') => void;
  selectedReportId: string | null;
  setSelectedReportId: (id: string | null) => void;
}

export default function AIHistoryView({ user, addToast, selectedReportId, setSelectedReportId }: AIHistoryProps) {
  const [reports, setReports] = useState<AIReport[]>([]);
  const [children, setChildren] = useState<Child[]>([]);
  const [loading, setLoading] = useState(true);
  const [searchQuery, setSearchQuery] = useState("");
  const [emailSending, setEmailSending] = useState(false);
  const [pdfDownloading, setPdfDownloading] = useState(false);
  const [copiedLink, setCopiedLink] = useState(false);

  // New states for sharing modals
  const [isEmailModalOpen, setIsEmailModalOpen] = useState(false);
  const [isWhatsAppModalOpen, setIsWhatsAppModalOpen] = useState(false);
  const [customEmail, setCustomEmail] = useState("");
  const [customPhone, setCustomPhone] = useState("");
  const [customMessage, setCustomMessage] = useState("");

  // Print Ref
  const printAreaRef = useRef<HTMLDivElement>(null);

  const loadReports = async () => {
    try {
      const data = await api.getAIReports();
      setReports(data);
      const kids = await api.getChildren();
      setChildren(kids);
    } catch (err: any) {
      addToast("Failed to load AI reports", err.message || "Error reading reports archive.", "error");
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    loadReports();
  }, []);

  // Sync selected observation view trigger
  const activeReport = reports.find(r => r.id === selectedReportId || r.observationId === selectedReportId);

  const handlePrint = () => {
    window.print();
  };

  const handleDownloadPDF = () => {
    if (!activeReport) return;
    setPdfDownloading(true);
    addToast("Generating Document", "Packaging milestones metadata and styling vectors...", "info");
    
    try {
      const reportTitle = `${activeReport.childName.replace(/\s+/g, '_')}_Developmental_Report`;
      
      const doc = new jsPDF("p", "mm", "a4");
      const margin = 15;
      let y = 25;
      let pageNum = 1;

      const checkPageSpace = (needed: number) => {
        if (y + needed > 270) {
          doc.addPage();
          pageNum++;
          // Header of new page
          doc.setDrawColor(226, 232, 240);
          doc.setLineWidth(0.5);
          doc.line(margin, 18, 195, 18);
          
          doc.setFont("Helvetica", "italic");
          doc.setFontSize(8);
          doc.setTextColor(148, 163, 184);
          doc.text("FirstCry Intellitots Brainery - Developmental Report", margin, 13);
          
          // Footer of new page
          doc.line(margin, 280, 195, 280);
          doc.text(`Page ${pageNum}`, 180, 285);
          doc.text("Confidential Student File - Generated by AI Assistant", margin, 285);
          
          y = 28;
        }
      };

      const addParagraph = (text: string, fontSize = 10, fontStyle = "normal", color = [30, 41, 59], spacing = 5) => {
        doc.setFont("Helvetica", fontStyle);
        doc.setFontSize(fontSize);
        doc.setTextColor(color[0], color[1], color[2]);
        const lines = doc.splitTextToSize(text, 180);
        for (const line of lines) {
          checkPageSpace(spacing);
          doc.text(line, margin, y);
          y += spacing;
        }
      };

      // --- FIRST PAGE BRANDING HEADER ---
      doc.setFont("Helvetica", "bold");
      doc.setFontSize(10);
      doc.setTextColor(59, 130, 246); // Blue branding
      doc.text("FIRSTCRY INTELLITOTS BRAINERY", margin, y);
      y += 6;

      doc.setFont("Helvetica", "bold");
      doc.setFontSize(14);
      doc.setTextColor(30, 41, 59); // Slate-800
      doc.text("AI CHILD OBSERVATION & DEVELOPMENT REPORT", margin, y);
      y += 8;

      // Divider line
      doc.setDrawColor(59, 130, 246);
      doc.setLineWidth(1);
      doc.line(margin, y, 195, y);
      y += 8;

      // --- PROFILE METADATA SECTION ---
      checkPageSpace(30);
      doc.setFillColor(248, 250, 252); // Slate-50 background card
      doc.rect(margin, y, 180, 28, "F");
      doc.setDrawColor(226, 232, 240);
      doc.setLineWidth(0.5);
      doc.rect(margin, y, 180, 28, "D");

      doc.setFont("Helvetica", "bold");
      doc.setFontSize(9);
      doc.setTextColor(148, 163, 184);
      doc.text("STUDENT PROFILE", margin + 5, y + 6);
      doc.text("ASSESSMENT DATA", margin + 95, y + 6);

      // Student Profile Info
      doc.setFont("Helvetica", "bold");
      doc.setFontSize(10);
      doc.setTextColor(71, 85, 105);
      doc.text(`Name: ${activeReport.childName}`, margin + 5, y + 13);
      doc.setFont("Helvetica", "normal");
      doc.text(`Grade Level: Pre-Playgroup`, margin + 5, y + 19);
      doc.text(`Assessed Level: Standard Preschool`, margin + 5, y + 25);

      // Report metadata
      doc.setFont("Helvetica", "normal");
      doc.text(`Ref ID: ${activeReport.id}`, margin + 95, y + 13);
      doc.text(`Date Generated: ${new Date(activeReport.dateGenerated).toLocaleDateString()}`, margin + 95, y + 19);
      doc.text(`Certified By: ${activeReport.generatedBy}`, margin + 95, y + 25);
      y += 36;

      // --- EXECUTIVE SUMMARY ---
      checkPageSpace(15);
      doc.setFont("Helvetica", "bold");
      doc.setFontSize(12);
      doc.setTextColor(15, 23, 42);
      doc.text("EXECUTIVE OBSERVATION SUMMARY", margin, y);
      y += 5;
      
      doc.setDrawColor(148, 163, 184);
      doc.setLineWidth(0.5);
      doc.line(margin, y, 195, y);
      y += 6;

      const summaryText = `"${activeReport.summary}"`;
      addParagraph(summaryText, 10, "italic", [71, 85, 105], 5.5);
      y += 4;

      // --- STRENGTHS & CONCERNS GRID ---
      checkPageSpace(50);
      const halfWidth = 86;
      
      // Strengths Box
      doc.setFillColor(240, 253, 244); // light green
      doc.rect(margin, y, halfWidth, 42, "F");
      doc.setDrawColor(187, 247, 208);
      doc.rect(margin, y, halfWidth, 42, "D");
      
      doc.setFont("Helvetica", "bold");
      doc.setFontSize(10);
      doc.setTextColor(21, 128, 61);
      doc.text("IDENTIFIED STRENGTHS", margin + 4, y + 6);
      
      let strY = y + 12;
      doc.setFont("Helvetica", "normal");
      doc.setFontSize(9);
      doc.setTextColor(30, 41, 59);
      
      const strengths = activeReport.strengths || [];
      if (strengths.length === 0) {
        doc.text("• No specific strengths noted.", margin + 4, strY);
      } else {
        strengths.slice(0, 4).forEach(s => {
          const lines = doc.splitTextToSize(`• ${s}`, halfWidth - 8);
          lines.forEach((line: string) => {
            if (strY < y + 38) {
              doc.text(line, margin + 4, strY);
              strY += 4.5;
            }
          });
        });
      }

      // Concerns Box
      doc.setFillColor(255, 251, 235); // light amber
      doc.rect(margin + 94, y, halfWidth, 42, "F");
      doc.setDrawColor(253, 230, 138);
      doc.rect(margin + 94, y, halfWidth, 42, "D");
      
      doc.setFont("Helvetica", "bold");
      doc.setFontSize(10);
      doc.setTextColor(180, 83, 9);
      doc.text("GROWTH ZONES & CONCERNS", margin + 98, y + 6);
      
      let conY = y + 12;
      doc.setFont("Helvetica", "normal");
      doc.setFontSize(9);
      doc.setTextColor(30, 41, 59);
      
      const concerns = activeReport.concerns || [];
      if (concerns.length === 0) {
        doc.text("• No growth concerns noted.", margin + 98, conY);
      } else {
        concerns.slice(0, 4).forEach(c => {
          const lines = doc.splitTextToSize(`• ${c}`, halfWidth - 8);
          lines.forEach((line: string) => {
            if (conY < y + 38) {
              doc.text(line, margin + 98, conY);
              conY += 4.5;
            }
          });
        });
      }
      y += 50;

      // --- MILESTONE DEVELOPMENT MATRIX ---
      checkPageSpace(15);
      doc.setFont("Helvetica", "bold");
      doc.setFontSize(12);
      doc.setTextColor(15, 23, 42);
      doc.text("MILESTONE DEVELOPMENT MATRIX", margin, y);
      y += 5;
      
      doc.setDrawColor(148, 163, 184);
      doc.setLineWidth(0.5);
      doc.line(margin, y, 195, y);
      y += 6;

      const matrix = activeReport.developmentNotes || {
        socialSkills: "N/A",
        learningProgress: "N/A",
        communicationSkills: "N/A",
        emotionalBehaviour: "N/A",
        confidenceLevel: "N/A"
      };

      const categories = [
        { label: "Social Skills", value: matrix.socialSkills },
        { label: "Learning Progress", value: matrix.learningProgress },
        { label: "Communication Skills", value: matrix.communicationSkills },
        { label: "Emotional Behaviour", value: matrix.emotionalBehaviour },
        { label: "Confidence Level", value: matrix.confidenceLevel }
      ];

      categories.forEach(cat => {
        checkPageSpace(15);
        doc.setFont("Helvetica", "bold");
        doc.setFontSize(9.5);
        doc.setTextColor(30, 41, 59);
        doc.text(cat.label, margin, y);
        y += 4.5;
        
        addParagraph(cat.value, 9, "normal", [71, 85, 105], 4.5);
        y += 2;
      });

      // --- PLAY-BASED ACTIVITIES ---
      checkPageSpace(20);
      doc.setFont("Helvetica", "bold");
      doc.setFontSize(12);
      doc.setTextColor(15, 23, 42);
      doc.text("RECOMMENDED CURRICULUM & HOMEWORK", margin, y);
      y += 5;
      
      doc.setDrawColor(148, 163, 184);
      doc.setLineWidth(0.5);
      doc.line(margin, y, 195, y);
      y += 6;

      // Home Play Suggestions
      checkPageSpace(12);
      doc.setFont("Helvetica", "bold");
      doc.setFontSize(10);
      doc.setTextColor(59, 130, 246);
      doc.text("Home Play & Family Homework Activities", margin, y);
      y += 6;

      const parentSugs = activeReport.parentSuggestions || [];
      if (parentSugs.length === 0) {
        addParagraph("• Collaborate with the school through continuous home reinforcement.", 9.5, "normal", [71, 85, 105], 4.5);
      } else {
        parentSugs.forEach(sug => {
          addParagraph(`• ${sug}`, 9.5, "normal", [71, 85, 105], 4.5);
        });
      }
      y += 4;

      // Classroom Interventions
      checkPageSpace(12);
      doc.setFont("Helvetica", "bold");
      doc.setFontSize(10);
      doc.setTextColor(99, 102, 241);
      doc.text("Clinical Classroom Interventions", margin, y);
      y += 6;

      const teacherRecs = activeReport.teacherRecommendations || [];
      if (teacherRecs.length === 0) {
        addParagraph("• Tailored standard pre-school interaction and behavioral guidance.", 9.5, "normal", [71, 85, 105], 4.5);
      } else {
        teacherRecs.forEach(rec => {
          addParagraph(`• ${rec}`, 9.5, "normal", [71, 85, 105], 4.5);
        });
      }
      y += 4;

      // Play-Based Curriculums Card
      checkPageSpace(25);
      doc.setFillColor(239, 246, 255); // light blue card
      doc.rect(margin, y, 180, 22, "F");
      doc.setDrawColor(191, 219, 254);
      doc.rect(margin, y, 180, 22, "D");

      doc.setFont("Helvetica", "bold");
      doc.setFontSize(9);
      doc.setTextColor(29, 78, 216);
      doc.text("RECOMMENDED PLAY-BASED EXPERIENTIAL ACTIVITIES", margin + 4, y + 5);

      const activities = activeReport.activities || [];
      doc.setFont("Helvetica", "normal");
      doc.setFontSize(8.5);
      doc.setTextColor(30, 41, 59);
      
      let actStr = activities.map(a => `• ${a}`).join("   |   ");
      const wrappedAct = doc.splitTextToSize(actStr, 172);
      let actY = y + 11;
      wrappedAct.forEach((line: string) => {
        doc.text(line, margin + 4, actY);
        actY += 4.5;
      });
      y += 28;

      // --- CLOSING REMARKS & CERTIFICATION ---
      checkPageSpace(25);
      doc.setDrawColor(226, 232, 240);
      doc.setLineWidth(0.5);
      doc.line(margin, y, 195, y);
      y += 6;

      addParagraph(`"${activeReport.overallSummary}"`, 9.5, "italic", [71, 85, 105], 4.5);
      y += 4;

      checkPageSpace(15);
      doc.setFont("Helvetica", "bold");
      doc.setFontSize(8);
      doc.setTextColor(16, 185, 129); // Green check
      doc.text("CERTIFIED FIRSTCRY DEVELOPMENT SUMMARY FILE", margin + 40, y);
      
      // Footer for final page
      doc.setFont("Helvetica", "italic");
      doc.setFontSize(8);
      doc.setTextColor(148, 163, 184);
      doc.text("FirstCry Intellitots Clinical Development Team - Secure Document Verification", margin + 30, y + 4);

      // Trigger automatic save to user's PC Downloads!
      doc.save(`${reportTitle}.pdf`);

      setPdfDownloading(false);
      addToast("Download Complete", `${reportTitle}.pdf has been saved to your PC Downloads!`, "success");
    } catch (err: any) {
      setPdfDownloading(false);
      addToast("Download Failed", err.message || "Failed to generate professional PDF.", "error");
    }
  };

  const handleOpenEmailModal = () => {
    const kid = children.find(c => c.id === activeReport?.childId);
    setCustomEmail(kid?.parentEmail || "");
    setIsEmailModalOpen(true);
  };

  const handleSendEmail = (e: React.FormEvent) => {
    e.preventDefault();
    if (!customEmail) {
      addToast("Validation Error", "Please provide a recipient email address.", "warning");
      return;
    }
    setEmailSending(true);
    addToast("Preparing Email", `Configuring SMTP gateway for parent delivery...`, "info");
    setTimeout(() => {
      setEmailSending(false);
      setIsEmailModalOpen(false);
      addToast("Email Dispatched", `Developmental Summary securely dispatched to ${customEmail}!`, "success");
    }, 1500);
  };

  const handleOpenWhatsAppModal = () => {
    const kid = children.find(c => c.id === activeReport?.childId);
    setCustomPhone(kid?.parentPhone || "");
    
    // Compose message
    const shareLink = `${window.location.origin}/share/report/${activeReport?.id}`;
    const strengthsText = activeReport?.strengths.slice(0, 2).map(s => `• ${s}`).join("\n") || "";
    const msg = `Hello! 🌟 This is ${user.name} from FirstCry Intellitots.

I am pleased to share the AI Developmental Report for ${activeReport?.childName}.

Executive Summary: "${activeReport?.summary}"

Strengths Identified:
${strengthsText}

Please tap on this secure link to view the certified milestone report in full:
${shareLink}`;

    setCustomMessage(msg);
    setIsWhatsAppModalOpen(true);
  };

  const handleSendWhatsApp = (e: React.FormEvent) => {
    e.preventDefault();
    if (!customPhone) {
      addToast("Validation Error", "Please provide a phone number.", "warning");
      return;
    }
    
    // Clean phone number: remove spaces, +, etc. except digits
    const cleaned = customPhone.replace(/[^\d]/g, "");
    
    // Create WhatsApp web share url
    const waUrl = `https://api.whatsapp.com/send?phone=${cleaned}&text=${encodeURIComponent(customMessage)}`;
    
    // Open in new tab
    window.open(waUrl, "_blank");
    setIsWhatsAppModalOpen(false);
    addToast("WhatsApp Link Prepared", `Opening chat for parent delivery to ${customPhone}...`, "success");
  };

  const handleShare = () => {
    setCopiedLink(true);
    navigator.clipboard.writeText(`${window.location.origin}/share/report/${activeReport?.id}`);
    addToast("Shareable Link Copied", "Encrypted child profile sharing link saved to clipboard.", "success");
    setTimeout(() => setCopiedLink(false), 3000);
  };

  // Filter Logic
  const filteredReports = reports.filter(rep =>
    rep.childName.toLowerCase().includes(searchQuery.toLowerCase()) ||
    rep.summary.toLowerCase().includes(searchQuery.toLowerCase()) ||
    rep.id.includes(searchQuery)
  );

  if (loading) {
    return (
      <div className="space-y-4 animate-pulse">
        <div className="h-10 bg-slate-200 rounded-lg w-1/4"></div>
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
          {[...Array(3)].map((_, i) => (
            <div key={i} className="h-60 bg-slate-100 rounded-xl"></div>
          ))}
        </div>
      </div>
    );
  }

  return (
    <div className="space-y-6 font-sans">
      <AnimatePresence mode="wait">
        {activeReport ? (
          // ================= DOCUMENT VIEWER LAYOUT =================
          <motion.div
            key="viewer"
            initial={{ opacity: 0, y: 15 }}
            animate={{ opacity: 1, y: 0 }}
            exit={{ opacity: 0, y: -15 }}
            className="space-y-6"
          >
            {/* Header / Actions Menu */}
            <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4 no-print border-b border-slate-200 pb-5">
              <button
                onClick={() => setSelectedReportId(null)}
                className="flex items-center gap-2 text-sm font-semibold text-slate-600 hover:text-slate-900 transition-colors self-start"
              >
                <ArrowLeft className="h-4.5 w-4.5" />
                <span>Back to Reports Archive</span>
              </button>

              <div className="flex flex-wrap gap-2.5">
                <button
                  onClick={handlePrint}
                  className="flex items-center gap-1.5 px-4 py-2 bg-white border border-slate-200 text-slate-700 hover:bg-slate-50 font-medium rounded-lg text-xs transition-colors"
                >
                  <Printer className="h-4 w-4 text-slate-400" />
                  <span>Print File</span>
                </button>

                <button
                  onClick={handleDownloadPDF}
                  disabled={pdfDownloading}
                  className="flex items-center gap-1.5 px-4 py-2 bg-white border border-slate-200 text-slate-700 hover:bg-slate-50 font-medium rounded-lg text-xs transition-colors disabled:opacity-50"
                >
                  {pdfDownloading ? (
                    <div className="h-3.5 w-3.5 border-2 border-slate-700 border-t-transparent rounded-full animate-spin"></div>
                  ) : (
                    <Download className="h-4 w-4 text-slate-400" />
                  )}
                  <span>Download PDF</span>
                </button>

                {user.role !== "Parent" && (
                  <>
                    <button
                      onClick={handleOpenEmailModal}
                      className="flex items-center gap-1.5 px-4 py-2 bg-white border border-slate-200 text-slate-700 hover:bg-slate-50 font-medium rounded-lg text-xs transition-colors"
                    >
                      <Mail className="h-4 w-4 text-slate-400" />
                      <span>Email Parent</span>
                    </button>

                    <button
                      onClick={handleOpenWhatsAppModal}
                      className="flex items-center gap-1.5 px-4 py-2 bg-emerald-50 hover:bg-emerald-100 border border-emerald-200 text-emerald-700 font-medium rounded-lg text-xs transition-colors"
                    >
                      <svg className="h-4 w-4 text-emerald-600" viewBox="0 0 24 24" fill="currentColor">
                        <path d="M.057 24l1.687-6.163c-1.041-1.804-1.588-3.849-1.587-5.946C.06 5.348 5.397.01 12.008.01c3.202.001 6.212 1.246 8.477 3.513 2.266 2.268 3.507 5.28 3.505 8.484-.004 6.657-5.34 11.997-11.953 11.997-2.005-.001-3.973-.502-5.713-1.455L0 24zm6.59-4.846c1.6.95 3.188 1.449 4.825 1.451 5.436 0 9.86-4.42 9.864-9.864.002-2.637-1.03-5.114-2.905-6.99C16.458 1.874 13.977 1.031 11.332 1.03 5.897 1.03 1.474 5.451 1.47 10.887c-.001 1.63.452 3.22 1.31 4.632l-1.019 3.722 3.816-.995a9.814 9.814 0 004.48 1.134zM17.306 14.17c-.302-.15-1.787-.882-2.048-.978-.264-.096-.456-.145-.648.145-.192.29-.744.978-.912 1.17-.168.193-.336.217-.638.067-.301-.15-1.272-.469-2.424-1.496-.897-.8-1.502-1.787-1.678-2.088-.178-.302-.019-.465.132-.615.136-.135.302-.35.453-.524.15-.174.2-.29.3-.483.1-.193.05-.362-.025-.512-.075-.15-.648-1.562-.888-2.143-.234-.564-.472-.488-.648-.497-.168-.008-.36-.01-.552-.01s-.504.072-.768.362c-.264.29-1.008.986-1.008 2.404s1.032 2.788 1.176 2.98c.144.193 2.037 3.111 4.931 4.364.688.298 1.226.476 1.646.609.692.22 1.32.19 1.82.115.556-.083 1.787-.732 2.04-1.442.253-.71.253-1.319.176-1.442-.075-.123-.277-.194-.579-.344z"/>
                      </svg>
                      <span>WhatsApp Parent</span>
                    </button>
                  </>
                )}

                <button
                  onClick={handleShare}
                  className="flex items-center gap-1.5 px-4 py-2 bg-blue-600 hover:bg-blue-500 text-white font-medium rounded-lg text-xs transition-colors shadow-sm"
                >
                  {copiedLink ? <Check className="h-4 w-4" /> : <Share2 className="h-4 w-4" />}
                  <span>{copiedLink ? "Link Copied" : "Share File"}</span>
                </button>
              </div>
            </div>

            {/* Premium Document Canvas */}
            <div
              ref={printAreaRef}
              className="bg-white rounded-xl border border-slate-200 shadow-xl p-8 max-w-4xl mx-auto space-y-8 print-page relative overflow-hidden"
            >
              {/* Premium Header Branding */}
              <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between border-b border-slate-200 pb-6 gap-4">
                <div className="space-y-1">
                  <div className="flex items-center gap-2 text-blue-600">
                    <Sparkles className="h-6 w-6" />
                    <span className="font-display font-bold text-lg tracking-tight uppercase">FirstCry Intellitots</span>
                  </div>
                  <h1 className="text-xl font-bold font-display text-slate-800 uppercase tracking-tight">
                    AI Child Observation & Development Report
                  </h1>
                </div>
                <div className="text-left sm:text-right text-xs text-slate-400 space-y-0.5">
                  <p>Document Ref: <strong className="font-mono text-slate-700 font-bold">{activeReport.id}</strong></p>
                  <p>Report Date: {new Date(activeReport.dateGenerated).toLocaleDateString(undefined, { year: 'numeric', month: 'long', day: 'numeric' })}</p>
                  <p>Certified by: {activeReport.generatedBy}</p>
                </div>
              </div>

              {/* Student Metadata Card */}
              <div className="grid grid-cols-2 sm:grid-cols-4 gap-4 p-5 bg-slate-50 border border-slate-200 rounded-lg text-xs">
                <div>
                  <span className="text-slate-400 font-semibold block uppercase tracking-wider text-[9px]">Student Name</span>
                  <strong className="text-slate-800 text-sm font-bold block mt-0.5">{activeReport.childName}</strong>
                </div>
                <div>
                  <span className="text-slate-400 font-semibold block uppercase tracking-wider text-[9px]">Classroom Grade</span>
                  <strong className="text-slate-800 font-bold block mt-1">Pre-Playgroup</strong>
                </div>
                <div>
                  <span className="text-slate-400 font-semibold block uppercase tracking-wider text-[9px]">Assessed Level</span>
                  <strong className="text-slate-800 font-bold block mt-1">Standard Preschool</strong>
                </div>
                <div>
                  <span className="text-slate-400 font-semibold block uppercase tracking-wider text-[9px]">Milestone Risk</span>
                  <span className={`inline-flex items-center gap-1 mt-1 px-2 py-0.5 rounded-full font-bold text-[10px] ${
                    activeReport.riskLevel === "High" ? "bg-red-50 text-red-700 border border-red-100" :
                    activeReport.riskLevel === "Medium" ? "bg-amber-50 text-amber-700 border border-amber-100" :
                    "bg-emerald-50 text-emerald-700 border border-emerald-100"
                  }`}>
                    {activeReport.riskLevel} Risk
                  </span>
                </div>
              </div>

              {/* Executive Summary */}
              <div className="space-y-2">
                <h3 className="font-display font-bold text-slate-800 text-sm uppercase tracking-wider border-b border-slate-200 pb-1">
                  Executive Observation Summary
                </h3>
                <p className="text-slate-700 text-sm leading-relaxed italic font-sans font-medium">
                  "{activeReport.summary}"
                </p>
              </div>

              {/* Strengths & Concerns Grid */}
              <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                <div className="space-y-3 p-5 bg-emerald-50/30 border border-emerald-200 rounded-lg">
                  <div className="flex items-center gap-1.5 text-emerald-700 font-bold text-xs uppercase tracking-wider mb-2">
                    <Heart className="h-4 w-4 text-emerald-500" />
                    <span>Identified Strengths & Assets</span>
                  </div>
                  <ul className="space-y-2 text-xs text-slate-700">
                    {activeReport.strengths.map((str, idx) => (
                      <li key={idx} className="flex gap-2 items-start leading-relaxed">
                        <span className="text-emerald-500 font-bold select-none shrink-0">•</span>
                        <span>{str}</span>
                      </li>
                    ))}
                  </ul>
                </div>

                <div className="space-y-3 p-5 bg-amber-50/30 border border-amber-200 rounded-lg">
                  <div className="flex items-center gap-1.5 text-amber-700 font-bold text-xs uppercase tracking-wider mb-2">
                    <AlertTriangle className="h-4 w-4 text-amber-500" />
                    <span>Growth Zones / Concerns</span>
                  </div>
                  <ul className="space-y-2 text-xs text-slate-700">
                    {activeReport.concerns.map((con, idx) => (
                      <li key={idx} className="flex gap-2 items-start leading-relaxed">
                        <span className="text-amber-500 font-bold select-none shrink-0">•</span>
                        <span>{con}</span>
                      </li>
                    ))}
                  </ul>
                </div>
              </div>

              {/* Child Developmental Notes Matrix */}
              <div className="space-y-4">
                <h3 className="font-display font-bold text-slate-800 text-sm uppercase tracking-wider border-b border-slate-200 pb-1">
                  Milestone Development Matrix
                </h3>
                <div className="space-y-3.5 text-xs text-slate-700">
                  <div className="grid grid-cols-1 sm:grid-cols-3 gap-1 py-1.5 border-b border-slate-200">
                    <strong className="text-slate-800 font-bold">Social Skills</strong>
                    <p className="sm:col-span-2 leading-relaxed font-medium">{activeReport.developmentNotes.socialSkills}</p>
                  </div>
                  <div className="grid grid-cols-1 sm:grid-cols-3 gap-1 py-1.5 border-b border-slate-200">
                    <strong className="text-slate-800 font-bold">Learning Progress</strong>
                    <p className="sm:col-span-2 leading-relaxed font-medium">{activeReport.developmentNotes.learningProgress}</p>
                  </div>
                  <div className="grid grid-cols-1 sm:grid-cols-3 gap-1 py-1.5 border-b border-slate-200">
                    <strong className="text-slate-800 font-bold">Communication Skills</strong>
                    <p className="sm:col-span-2 leading-relaxed font-medium">{activeReport.developmentNotes.communicationSkills}</p>
                  </div>
                  <div className="grid grid-cols-1 sm:grid-cols-3 gap-1 py-1.5 border-b border-slate-200">
                    <strong className="text-slate-800 font-bold">Emotional Behaviour</strong>
                    <p className="sm:col-span-2 leading-relaxed font-medium">{activeReport.developmentNotes.emotionalBehaviour}</p>
                  </div>
                  <div className="grid grid-cols-1 sm:grid-cols-3 gap-1 py-1.5">
                    <strong className="text-slate-800 font-bold">Confidence Level</strong>
                    <p className="sm:col-span-2 leading-relaxed font-medium">{activeReport.developmentNotes.confidenceLevel}</p>
                  </div>
                </div>
              </div>

              {/* Homework and Interventions suggestions */}
              <div className="grid grid-cols-1 md:grid-cols-2 gap-6 pt-2 border-t border-slate-200">
                <div className="space-y-3">
                  <strong className="text-slate-800 font-bold text-xs uppercase tracking-wider block mb-1">Homework & Home Play</strong>
                  <ul className="space-y-2 text-xs text-slate-600">
                    {activeReport.parentSuggestions.map((sug, idx) => (
                      <li key={idx} className="flex gap-2 items-start">
                        <span className="text-blue-500 font-bold shrink-0 select-none">•</span>
                        <span>{sug}</span>
                      </li>
                    ))}
                  </ul>
                </div>

                <div className="space-y-3">
                  <strong className="text-slate-800 font-bold text-xs uppercase tracking-wider block mb-1">Classroom Interventions</strong>
                  <ul className="space-y-2 text-xs text-slate-600">
                    {activeReport.teacherRecommendations.map((rec, idx) => (
                      <li key={idx} className="flex gap-2 items-start">
                        <span className="text-indigo-500 font-bold shrink-0 select-none">•</span>
                        <span>{rec}</span>
                      </li>
                    ))}
                  </ul>
                </div>
              </div>

              {/* Play-Based Home Activities */}
              <div className="p-4 bg-blue-50/30 border border-blue-200 rounded-lg space-y-2">
                <span className="text-[10px] font-bold text-blue-600 uppercase tracking-wider block">Recommended Play-Based Curriculums</span>
                <div className="flex flex-col sm:flex-row gap-4">
                  {activeReport.activities.map((act, idx) => (
                    <div key={idx} className="flex-1 p-3 bg-white rounded-lg border border-slate-200 flex gap-2 text-xs text-slate-600">
                      <Sparkles className="h-4 w-4 text-blue-500 shrink-0 mt-0.5" />
                      <span>{act}</span>
                    </div>
                  ))}
                </div>
              </div>

              {/* Empowering Closing statement */}
              <div className="pt-6 border-t border-slate-200 text-center space-y-2">
                <p className="text-slate-600 text-xs leading-relaxed max-w-2xl mx-auto font-medium">
                  "{activeReport.overallSummary}"
                </p>
                <div className="pt-4 flex items-center justify-center gap-6 text-[10px] text-slate-400 font-semibold uppercase tracking-wider">
                  <span className="flex items-center gap-1"><ShieldCheck className="h-4 w-4 text-emerald-500" /> FirstCry certified</span>
                  <span>•</span>
                  <span>Confidential Student File</span>
                </div>
              </div>
            </div>
          </motion.div>
        ) : (
          // ================= ARCHIVE LIST LAYOUT =================
          <motion.div
            key="archive"
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            className="space-y-6"
          >
            <div>
              <h1 className="font-display text-2xl font-bold tracking-tight text-slate-900">Reports Archive</h1>
              <p className="text-slate-500 text-sm mt-1">Search, print, download, and email generated child milestones development summaries.</p>
            </div>

            {/* Search filter */}
            <div className="bg-white p-4 rounded-xl border border-slate-200 shadow-sm">
              <div className="relative">
                <div className="absolute inset-y-0 left-0 pl-3.5 flex items-center pointer-events-none text-slate-400">
                  <Search className="h-5 w-5" />
                </div>
                <input
                  type="text"
                  placeholder="Search reports by student name, ID, or keywords..."
                  value={searchQuery}
                  onChange={(e) => setSearchQuery(e.target.value)}
                  className="block w-full pl-10 pr-4 py-2 bg-slate-50 border border-slate-200 rounded-lg text-slate-800 placeholder-slate-400 focus:outline-none focus:ring-2 focus:ring-blue-500/15 focus:border-blue-500 transition-all text-sm"
                />
              </div>
            </div>

            {/* Reports list */}
            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
              {filteredReports.map(rep => (
                <motion.div
                  key={rep.id}
                  whileHover={{ y: -4 }}
                  onClick={() => setSelectedReportId(rep.id)}
                  className="bg-white p-5 rounded-xl border border-slate-200 hover:border-blue-300 hover:shadow-md cursor-pointer flex flex-col justify-between transition-all duration-300 relative overflow-hidden group"
                >
                  <div className="space-y-3.5">
                    <div className="flex items-center justify-between">
                      <span className="text-[10px] font-mono font-bold text-slate-400">{rep.id}</span>
                      <span className="text-[10px] font-semibold text-blue-600 bg-blue-50 px-2 py-0.5 rounded-full">
                        {new Date(rep.dateGenerated).toLocaleDateString()}
                      </span>
                    </div>

                    <div className="space-y-1">
                      <h3 className="font-display font-bold text-slate-900 group-hover:text-blue-600 transition-colors">
                        {rep.childName}
                      </h3>
                      <p className="text-xs text-slate-400 font-semibold uppercase tracking-wider">Milestones Report</p>
                    </div>

                    {/* Report summary clipping */}
                    <p className="text-xs text-slate-600 leading-relaxed line-clamp-3 bg-slate-50 p-3 rounded-lg border border-slate-200">
                      "{rep.summary}"
                    </p>
                  </div>

                  <div className="mt-4 pt-3 border-t border-slate-200 flex items-center justify-between text-xs font-semibold text-slate-400">
                    <span>By: <strong className="text-slate-600">{rep.generatedBy}</strong></span>
                    <span className="text-blue-600 group-hover:translate-x-1 transition-transform inline-flex items-center gap-1">
                      <span>View File</span>
                      <ArrowLeft className="h-3.5 w-3.5 rotate-180" />
                    </span>
                  </div>
                </motion.div>
              ))}

              {filteredReports.length === 0 && (
                <div className="col-span-full py-16 bg-white border border-dashed border-slate-200 rounded-xl flex flex-col items-center justify-center text-center px-4">
                  <span className="text-slate-300 text-5xl mb-4">📂</span>
                  <h3 className="font-display font-bold text-slate-700 text-base">No Reports Saved</h3>
                  <p className="text-xs text-slate-400 mt-1 max-w-sm">No child developmental summaries match your criteria. Head to observations to analyze standard teacher notes using Gemini AI.</p>
                </div>
              )}
            </div>
          </motion.div>
        )}
      </AnimatePresence>

      {/* Email Parent Modal */}
      <AnimatePresence>
        {isEmailModalOpen && (
          <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-slate-900/60 backdrop-blur-xs">
            <motion.div
              initial={{ opacity: 0, scale: 0.95 }}
              animate={{ opacity: 1, scale: 1 }}
              exit={{ opacity: 0, scale: 0.95 }}
              className="bg-white rounded-xl shadow-2xl border border-slate-100 max-w-md w-full overflow-hidden"
            >
              <div className="flex items-center justify-between px-5 py-4 border-b border-slate-100 bg-slate-50/50">
                <div className="flex items-center gap-2 text-slate-800">
                  <Mail className="h-5 w-5 text-blue-600" />
                  <h3 className="font-display font-bold text-sm">Email Report to Parent</h3>
                </div>
                <button
                  type="button"
                  onClick={() => setIsEmailModalOpen(false)}
                  className="p-1 text-slate-400 hover:text-slate-600 rounded-lg hover:bg-slate-100 transition-colors"
                >
                  <X className="h-4.5 w-4.5" />
                </button>
              </div>

              <form onSubmit={handleSendEmail} className="p-5 space-y-4">
                <div className="space-y-1.5">
                  <label className="block text-xs font-semibold text-slate-600">Parent/Guardian Email *</label>
                  <input
                    type="email"
                    required
                    value={customEmail}
                    onChange={(e) => setCustomEmail(e.target.value)}
                    className="block w-full px-3.5 py-2 bg-slate-50 border border-slate-200 rounded-lg text-slate-800 placeholder-slate-400 focus:outline-none focus:ring-2 focus:ring-blue-500/15 focus:border-blue-500 text-sm"
                    placeholder="e.g. parent@firstcry.com"
                  />
                  {!customEmail && (
                    <p className="text-xs text-amber-600 flex items-center gap-1 font-medium mt-1">
                      <span>⚠️ Guardian has no pre-saved email. Please type one to send.</span>
                    </p>
                  )}
                </div>

                <div className="space-y-1.5">
                  <label className="block text-xs font-semibold text-slate-600">Subject Preview</label>
                  <div className="px-3 py-2 bg-slate-50 border border-slate-100 rounded-lg text-xs text-slate-500 font-medium">
                    [FirstCry Intellitots] AI Milestone & Developmental Report for {activeReport?.childName}
                  </div>
                </div>

                <div className="space-y-1.5">
                  <label className="block text-xs font-semibold text-slate-600">Report Excerpt</label>
                  <div className="p-3 bg-slate-50 border border-slate-100 rounded-lg text-xs text-slate-600 max-h-32 overflow-y-auto leading-relaxed">
                    "{activeReport?.summary}"
                  </div>
                </div>

                <div className="pt-3 border-t border-slate-100 flex items-center justify-end gap-2.5">
                  <button
                    type="button"
                    onClick={() => setIsEmailModalOpen(false)}
                    className="px-4 py-2 text-xs font-semibold text-slate-500 hover:text-slate-800 transition-colors"
                  >
                    Cancel
                  </button>
                  <button
                    type="submit"
                    disabled={emailSending}
                    className="flex items-center gap-1.5 px-4 py-2 bg-blue-600 hover:bg-blue-500 text-white font-semibold rounded-lg text-xs transition-colors shadow-sm disabled:opacity-50"
                  >
                    {emailSending ? (
                      <div className="h-3.5 w-3.5 border-2 border-white border-t-transparent rounded-full animate-spin"></div>
                    ) : (
                      <Mail className="h-4 w-4" />
                    )}
                    <span>Send Email Report</span>
                  </button>
                </div>
              </form>
            </motion.div>
          </div>
        )}
      </AnimatePresence>

      {/* WhatsApp Parent Modal */}
      <AnimatePresence>
        {isWhatsAppModalOpen && (
          <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-slate-900/60 backdrop-blur-xs">
            <motion.div
              initial={{ opacity: 0, scale: 0.95 }}
              animate={{ opacity: 1, scale: 1 }}
              exit={{ opacity: 0, scale: 0.95 }}
              className="bg-white rounded-xl shadow-2xl border border-slate-100 max-w-md w-full overflow-hidden"
            >
              <div className="flex items-center justify-between px-5 py-4 border-b border-slate-100 bg-emerald-50/50">
                <div className="flex items-center gap-2 text-emerald-800">
                  <svg className="h-5 w-5 text-emerald-600" viewBox="0 0 24 24" fill="currentColor">
                    <path d="M.057 24l1.687-6.163c-1.041-1.804-1.588-3.849-1.587-5.946C.06 5.348 5.397.01 12.008.01c3.202.001 6.212 1.246 8.477 3.513 2.266 2.268 3.507 5.28 3.505 8.484-.004 6.657-5.34 11.997-11.953 11.997-2.005-.001-3.973-.502-5.713-1.455L0 24zm6.59-4.846c1.6.95 3.188 1.449 4.825 1.451 5.436 0 9.86-4.42 9.864-9.864.002-2.637-1.03-5.114-2.905-6.99C16.458 1.874 13.977 1.031 11.332 1.03 5.897 1.03 1.474 5.451 1.47 10.887c-.001 1.63.452 3.22 1.31 4.632l-1.019 3.722 3.816-.995a9.814 9.814 0 004.48 1.134zM17.306 14.17c-.302-.15-1.787-.882-2.048-.978-.264-.096-.456-.145-.648.145-.192.29-.744.978-.912 1.17-.168.193-.336.217-.638.067-.301-.15-1.272-.469-2.424-1.496-.897-.8-1.502-1.787-1.678-2.088-.178-.302-.019-.465.132-.615.136-.135.302-.35.453-.524.15-.174.2-.29.3-.483.1-.193.05-.362-.025-.512-.075-.15-.648-1.562-.888-2.143-.234-.564-.472-.488-.648-.497-.168-.008-.36-.01-.552-.01s-.504.072-.768.362c-.264.29-1.008.986-1.008 2.404s1.032 2.788 1.176 2.98c.144.193 2.037 3.111 4.931 4.364.688.298 1.226.476 1.646.609.692.22 1.32.19 1.82.115.556-.083 1.787-.732 2.04-1.442.253-.71.253-1.319.176-1.442-.075-.123-.277-.194-.579-.344z" />
                  </svg>
                  <h3 className="font-display font-bold text-sm">Send WhatsApp Report</h3>
                </div>
                <button
                  type="button"
                  onClick={() => setIsWhatsAppModalOpen(false)}
                  className="p-1 text-slate-400 hover:text-slate-600 rounded-lg hover:bg-slate-100 transition-colors"
                >
                  <X className="h-4.5 w-4.5" />
                </button>
              </div>

              <form onSubmit={handleSendWhatsApp} className="p-5 space-y-4">
                <div className="space-y-1.5">
                  <label className="block text-xs font-semibold text-slate-600">WhatsApp Number *</label>
                  <input
                    type="text"
                    required
                    value={customPhone}
                    onChange={(e) => setCustomPhone(e.target.value)}
                    className="block w-full px-3.5 py-2 bg-slate-50 border border-slate-200 rounded-lg text-slate-800 placeholder-slate-400 focus:outline-none focus:ring-2 focus:ring-emerald-500/15 focus:border-emerald-500 text-sm"
                    placeholder="e.g. +91 98123 45678"
                  />
                  {!customPhone && (
                    <p className="text-xs text-amber-600 flex items-center gap-1 font-medium mt-1">
                      <span>⚠️ Guardian has no pre-saved phone. Please type any phone number.</span>
                    </p>
                  )}
                </div>

                <div className="space-y-1.5">
                  <label className="block text-xs font-semibold text-slate-600">Pre-Composed Message</label>
                  <textarea
                    rows={8}
                    required
                    value={customMessage}
                    onChange={(e) => setCustomMessage(e.target.value)}
                    className="block w-full px-3.5 py-2 bg-slate-50 border border-slate-200 rounded-lg text-slate-800 placeholder-slate-400 focus:outline-none focus:ring-2 focus:ring-emerald-500/15 focus:border-emerald-500 text-xs font-mono leading-relaxed resize-none"
                  />
                </div>

                <div className="p-3 bg-slate-50 rounded-lg text-slate-500 text-[11px] leading-relaxed">
                  💡 This generates a custom WhatsApp link that securely opens inside the WhatsApp app or WhatsApp Web, loaded with your pre-written message and direct report link.
                </div>

                <div className="pt-3 border-t border-slate-100 flex items-center justify-end gap-2.5">
                  <button
                    type="button"
                    onClick={() => setIsWhatsAppModalOpen(false)}
                    className="px-4 py-2 text-xs font-semibold text-slate-500 hover:text-slate-800 transition-colors"
                  >
                    Cancel
                  </button>
                  <button
                    type="submit"
                    className="flex items-center gap-1.5 px-4 py-2 bg-emerald-600 hover:bg-emerald-500 text-white font-semibold rounded-lg text-xs transition-colors shadow-sm"
                  >
                    <svg className="h-4 w-4" viewBox="0 0 24 24" fill="currentColor">
                      <path d="M.057 24l1.687-6.163c-1.041-1.804-1.588-3.849-1.587-5.946C.06 5.348 5.397.01 12.008.01c3.202.001 6.212 1.246 8.477 3.513 2.266 2.268 3.507 5.28 3.505 8.484-.004 6.657-5.34 11.997-11.953 11.997-2.005-.001-3.973-.502-5.713-1.455L0 24zm6.59-4.846c1.6.95 3.188 1.449 4.825 1.451 5.436 0 9.86-4.42 9.864-9.864.002-2.637-1.03-5.114-2.905-6.99C16.458 1.874 13.977 1.031 11.332 1.03 5.897 1.03 1.474 5.451 1.47 10.887c-.001 1.63.452 3.22 1.31 4.632l-1.019 3.722 3.816-.995a9.814 9.814 0 004.48 1.134zM17.306 14.17c-.302-.15-1.787-.882-2.048-.978-.264-.096-.456-.145-.648.145-.192.29-.744.978-.912 1.17-.168.193-.336.217-.638.067-.301-.15-1.272-.469-2.424-1.496-.897-.8-1.502-1.787-1.678-2.088-.178-.302-.019-.465.132-.615.136-.135.302-.35.453-.524.15-.174.2-.29.3-.483.1-.193.05-.362-.025-.512-.075-.15-.648-1.562-.888-2.143-.234-.564-.472-.488-.648-.497-.168-.008-.36-.01-.552-.01s-.504.072-.768.362c-.264.29-1.008.986-1.008 2.404s1.032 2.788 1.176 2.98c.144.193 2.037 3.111 4.931 4.364.688.298 1.226.476 1.646.609.692.22 1.32.19 1.82.115.556-.083 1.787-.732 2.04-1.442.253-.71.253-1.319.176-1.442-.075-.123-.277-.194-.579-.344z"/>
                    </svg>
                    <span>Send to WhatsApp</span>
                  </button>
                </div>
              </form>
            </motion.div>
          </div>
        )}
      </AnimatePresence>
    </div>
  );
}
